### ISSUE TITLE
Web component & Polymer implemtations in Edge not displaying

### ISSUE THREAD

**Issue by bburch** [craigshoemaker/jquery-to-polymer#2]
All implementations are display in Chrome.

The error in Edge, Polymer implementation: "Object doesn't support property or method 'init'" It looks to be referring to the init in the script of slide-nav.html.

There is not any error display in the Web Component implementation. This dialog box display in the debugging tab of the developer tool: "Could not locate http://127.0.0.1:8080/bower_components/webcomponentsjs/ [synthetic:util/global] specified in source map http://127.0.0.1:8080/bower_components/webcomponentsjs/webcomponents-lite.js.map." Neither a onload function nor a onerror function display any message in the console.

Any suggestions on getting these two implementations to work in Edge?

Thank you,
Brandon

**Comment by craigshoemaker** [comment]
Unfortunately [Edge currently does not support](https://caniuse.com/#search=web%20components) any of the APIs that make up Web Components 😞
